In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [2]:
np.random.randint(2, size=4)

array([0, 1, 0, 0])

In [3]:
np.random.randint(1, size=4)

array([0, 0, 0, 0])

In [4]:
np.random.randint(4, size=4)

array([1, 0, 3, 0])

In [5]:
np.random.randint(20, size=4)

array([15, 14,  5, 17])

In [6]:
# Do this (new version)
from numpy.random import default_rng
rng = default_rng()
vals = rng.standard_normal(10)
more_vals = rng.standard_normal(10)


In [7]:
more_vals

array([-0.05304708, -0.38996184,  1.71311626,  0.81719734,  1.70184556,
        0.08406176,  0.84364647, -0.81721531, -0.21026405, -0.93698757])

In [8]:
rng

Generator(PCG64) at 0x7FECB134B500

In [16]:
np.random.rand(5,4)

array([[0.61861457, 0.0626993 , 0.55715021, 0.03913053],
       [0.30841474, 0.63795136, 0.35949502, 0.88834548],
       [0.98829406, 0.51682999, 0.34032836, 0.43589469],
       [0.5944845 , 0.42920732, 0.84465723, 0.84337559],
       [0.83025012, 0.25808711, 0.23650955, 0.95453492]])

In [14]:
# random.choice(a, size=None, replace=True, p=None)
#p1-D array-like, optional
#The probabilities associated with each entry in a. If not given the sample assumes a uniform distribution over all entries in a.


In [10]:
np.random.choice(5, 3, replace=False)

array([1, 4, 0])

In [29]:
np.random.choice((1,5), 3)

array([1, 1, 5])

In [12]:
np.random.randint(0,5,5)

array([0, 1, 3, 1, 4])

In [13]:
np.random.choice(5, 3, replace=False, p=[0.1, 0, 0.3, 0.6, 0])

array([2, 3, 0])

In [25]:
#Generetor
rng = np.random.default_rng()
n, p = 100, .1
# result of flipping a coin 10 times, tested 1000 times.
rng.binomial(n, p, 10)


array([ 7, 12, 12,  8,  8, 10, 15,  7, 14,  8])

In [27]:
rng.normal(n, p, 10)

array([ 99.8783506 , 100.01182067, 100.06536278,  99.87671252,
        99.95396894,  99.97102969, 100.11542258,  99.9651582 ,
        99.9435173 , 100.18528084])